jobs:
  include:
    - stage: functionality
      language: python
      sudo: required
      services:
        - docker
      env:
        - CODALAB_USERNAME=codalab CODALAB_PASSWORD=testpassword CODALAB_ROOT_PASSWORD=testpassword CI=false CODALAB_SERVICE_HOME=/home/travis/codalab/home/ CODALAB_MYSQL_MOUNT=/home/travis/codalab/mysql/ CODALAB_WORKER_DIR=/home/travis/codalab/worker-dir/ CODALAB_VERSION=${TRAVIS_BRANCH}
      python: 2.7
      before_install:
        - sudo rm /usr/local/bin/docker-compose
        - curl -L https://github.com/docker/compose/releases/download/1.23.2/docker-compose-`uname -s`-`uname -m` > docker-compose
        - chmod +x docker-compose
        - sudo mv docker-compose /usr/local/bin
      install:
        - pip install --upgrade pip MySQL-python
        - ./codalab-service.py build -v ${TRAVIS_BRANCH} --push
        - ./setup.sh server
      script:
        - ./codalab-service.py -i -w -t
    - stage: style
      language: python
      python: 3.6
      install: pip install --upgrade black==18.9b0
      script: black . --check
    - stage: deploy
      script: echo "Deploying"
      language: python
      sudo: required
      services:
        - docker
      env:
        - CODALAB_USERNAME=codalab CODALAB_PASSWORD=testpassword CI=false
      python: 2.7
      after_success: echo "skipped"
      before_deploy:
        - pip install twine
      deploy:
        # Build docker images using tag if it's a version tag (we're releasing)
        # Otherwise if we're on master or staging build named images
        - provider: script
          # Remove first char of tag (v) to get version number from tag
          script: ./scripts/travis-deploy.sh ${TRAVIS_TAG#?} release
          on:
            # only build on valid semver tags
            tags: true
            condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+
        - provider: script
          # Build with branch name if not releasing
          script: ./scripts/travis-deploy.sh master
          on:
            # only build for master and staging for debugging
            branch: master
