version: '3.5'

x-non-blocking-logging:
  &non-blocking-logging
  driver: json-file
  options:
    mode: non-blocking

x-codalab-env:
  &codalab-env
  - CODALAB_HOME=${CODALAB_SERVICE_HOME}
  - CODALAB_USERNAME=${CODALAB_ROOT_USER}
  - CODALAB_PASSWORD=${CODALAB_ROOT_PWD}

services:
  mysql:
    image: mysql:5.5.53
    environment:
      - MYSQL_ROOT_PASSWORD=${CODALAB_MYSQL_ROOT_PWD}
      - MYSQL_DATABASE=codalab_bundles
      - MYSQL_USER=${CODALAB_MYSQL_USER}
      - MYSQL_PASSWORD=${CODALAB_MYSQL_PWD}
    networks:
      - service
    logging:
      *non-blocking-logging

  rest-server:
    image: codalab/bundleserver:${CODALAB_VERSION}
    command: server
    environment:
      *codalab-env
    volumes:
      - ./files/wait-for-it.sh:/data/bin/wait-for-it.sh
    depends_on:
      - mysql
    networks:
      - service
    logging:
      *non-blocking-logging

  bundle-manager:
    image: codalab/bundleserver:${CODALAB_VERSION}
    command: bundle-manager
    environment:
      *codalab-env
    volumes:
      - ./files/wait-for-it.sh:/data/bin/wait-for-it.sh
    depends_on:
      - rest-server
    networks:
      - service
    logging:
      *non-blocking-logging

  frontend:
    image: codalab/frontend:${CODALAB_VERSION}
    depends_on:
      - rest-server
    networks:
      - service
    logging:
      *non-blocking-logging

  nginx:
    image: nginx:1.12.0
    command: /data/bin/wait-for-it.sh rest-server:2900 -- nginx
    ports:
      - ${CODALAB_HTTP_PORT}:80
    volumes:
      - ./files/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./files/wait-for-it.sh:/data/bin/wait-for-it.sh
    depends_on:
      - frontend
    networks:
      - service
    logging:
      *non-blocking-logging

  worker:
    image: codalab/worker:${CODALAB_VERSION}
    command: --server http://rest-server:2900 --verbose --work-dir ${CODALAB_WORKER_DIR} --network-prefix ${CODALAB_WORKER_NETWORK_NAME}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      *codalab-env
    depends_on:
      - bundle-manager
    networks:
      - service
      - worker
    logging:
      *non-blocking-logging

  tests:
    image: codalab/bundleserver:${CODALAB_VERSION}
    working_dir: /opt/codalab-worksheets/
    entrypoint: ./venv/bin/python ./test-cli.py
    command: all --instance http://rest-server:2900
    environment:
      *codalab-env
    depends_on:
      - rest-server
    networks:
      - service
    logging:
      *non-blocking-logging

networks:
  worker:
    name: ${CODALAB_WORKER_NETWORK_NAME}
    internal: True
  service:
